[package]
name = "spiderq"
version = "0.0.6"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
getopts = "*"
byteorder = "*"
time = "*"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }
