[package]
name = "spiderq"
version = "1.0.0"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
getopts = "*"
byteorder = "*"
time = "*"
tempdir = "*"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }
spiderq_proto = { git = "git://dev.swizard.info/spiderq-proto" }

[dev-dependencies]
rand = "*"
