[package]
name = "spiderq"
version = "1.2.0"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
getopts = "*"
byteorder = "*"
time = "*"
tempdir = "*"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }
spiderq_proto = { path = "spiderq-proto" }

[dev-dependencies]
rand = "*"
